# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bf77e6a3d672ab6da710438249212350a555f6429da97e885c3a640ee3b818af4f11eec72035737dd1f23a44c8a3dd59bc23e7d8b28e9aba9761083b304e413

test:
  secret_key_base: 86a8d9c2cd1595d722240920d2f2a0c3e76f55f41bb8ec69b222ae59030f27e4c0e4ca6b19deb23a12bf601abfd380c5321caf580bbd64decc9e12704bedeee6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
